window.T = window.T || {};
window.T.language = window.T.language || {};

window.T.language['fr-FR'] = {
    id: 'fr-FR',
    elements: {
        id: 'fr-FR',
        success: {
            ingredients: 'Ingrédients',
            name: 'Nom',
            title: 'Que souhaitez vous créer ?',
            recipes: 'Recettes',
            by_name: 'Par nom',
            by_ingredients: 'Par ingrédients',
            search: 'Recherche',
            see_results: 'Voir les résultats en',
            select_language: 'Langue par défaut',
            multi_language_results: 'Résultat multi langue',
            multi_language_results_description: 'Cherchera dans toutes les langues disponibles (chercher "plank" retrouvera "planches")',
            yes: 'Oui',
            no: 'Non',
            mods: 'Mods',
            mod: 'Mod',
            lightmod: 'Minifié',
        },
        error: {
            by_name: 'Désolé mais nous n\'avons rien trouvé par nom !',
            by_ingredients: 'Désolé mais nous n\'avons rien trouvé par ingrédients !',
        },
    },
    recipes: {
        id: 'fr-FR',
        american_apple_crate: "Caisse de pommes américaines",
        animal_lard: "Saindoux",
        apple_crate: "Caisse de pomme",
        bandage: "Bandage",
        bannermount: "Bannermount",
        banners: "Bannières",
        barbwire: "Barbelé",
        barbwire_baseball_bat: "Batte de baseball barbelée",
        bark_birch: "Bouleau écorce",
        bark_oak: "Chêne écorce",
        barrel_frame: "Cadre de baril",
        baseball_bat: "Batte de baseball",
        bearfur_cowl: "Capuche en fourrure d'ours",
        bearpelt: "Peau d'ours",
        bone_fishing_hook: "Crochet de pêche en os",
        bones: "Os",
        bullet: "Balle",
        burlap_sack: "Sac de jute",
        burlap_strips: "Bandes de jute",
        camonet: "Camonet",
        cannabis: "Cannabis",
        cannabis_bag: "Sac de cannabis",
        cannabis_brick: "Brique de cannabis",
        cigarettes: "Cigarettes",
        darkwood_water_barrel: "Baril d'eau en bois foncé",
        darkwood_water_barrel_stand: "Support de baril d'eau en bois foncé",
        darkwood_water_barrel_valve: "Vanne à baril d'eau en bois foncé",
        decoy_grenade: "Grenade leurre",
        deer_pelt: "Peau de cerf",
        duct_tape: "Ruban adhésif",
        epoxy_putty: "Mastic époxy",
        fireplace: "Cheminée",
        fireplace_railing: "Garde-corps de cheminée",
        firewood: "Bois de chauffage",
        food_item: "Produit alimentaire",
        garden_lime: "Engrais",
        gardenbox: "Jardinière",
        ghillie_bushrag: "Ghillie bushrag",
        ghillie_gun_wrap: "Enveloppe de pistolet ghillie",
        ghillie_hood: "Capuche ghillie",
        ghillie_suit: "Costume ghillie",
        ghillie_top: "Haut ghillie",
        gunwall_metal: "Présentoir d'arme en métal",
        gunwall_wood: "Présentoir d'arme en bois",
        hammer: "Marteau",
        hand_drill_kit: "Allume feu",
        improvised_courier_backpack: "Sac à dos improvisé",
        improvised_courier_bag: "Sac improvisé",
        improvised_fishing_rod: "Canne à pêche improvisée",
        improvised_leather_backpack: "Sac à dos en cuir improvisé",
        improvised_leather_bag: "Sac en cuir improvisé",
        improvised_suppressor: "Silencieux improvisé",
        improvised_tent: "Tente improvisée",
        jest_wonderbread: "Jest Wonderbread",
        joint: "Joint",
        knife: "Couteau",
        large_ammo_box: "Grande boîte de munitions",
        leather_courier_bag: "Sac en cuir",
        leather_hat: "Chapeau en cuir",
        leather_jacket: "Veste de cuir",
        leather_moccassins: "Mocassins en cuir",
        leather_pants: "Pantalon en cuir",
        leather_sack: "Sac en cuir",
        leather_sewing_kit: "Kit couture cuir",
        leather_storage_vest: "Gilet de rangement en cuir",
        leather_water_pouch: "Gourde eau en cuir",
        locker: "Casier",
        long_wooden_stick: "Long bâton en bois",
        make_shift_tent_a: "Tente improvisée",
        make_shift_tent_b: "Tente improvisée",
        marijuana_cigarettes: "Cigarettes de marijuana",
        metal_plates: "Plaques métalliques",
        metalwire: "Fil de fer",
        nails: "Clous",
        netting: "Filets",
        paper: "Papier",
        pet_bottle: "Bouteille d'eau",
        pickaxe: "Pioche",
        pile_of_guts: "Tas de tripes",
        planks: "Planches",
        planter_box: "Jardinière",
        plants_material: "Matériel végétal",
        pliers: "Pinces",
        poncho_ghillie: "Poncho ghillie",
        rope: "Corde",
        sandwich: "Sandwich",
        sewing_kit: "Kit de couture",
        shed_crafting_kit: "Kit de fabrication de hangar",
        small_stone: "Petite pierre",
        sodacan: "Canette de soda",
        spiked_baseball_bat: "Batte de baseball à pointes",
        splint: "Attelle",
        square_planter_box: "Jardinière carrée",
        stone: "Pierre",
        tag_ammo: "Etiquette de munitions",
        tag_clothing: "Etiquette de vêtements",
        tag_component: "Etiquette de composant",
        tag_construction: "Etiquette de construction",
        tag_magazine: "Etiquette de magazine",
        tag_medical: "Etiquette médicale",
        tag_tools: "Etiquette d'outils",
        tag_weapon: "Etiquette d'arme",
        tanned_leather: "Cuir tanné",
        tobacco: "Tabac",
        torch: "Torche",
        tripwire_trap: "Piège tripwire",
        water_barrel: "Baril d'eau",
        water_barrel_stand: "Support de baril d'eau",
        water_barrel_valve: "Vanne à baril d'eau",
        wild_boar_pelt: "Peau de sanglier",
        wolffur_cowl: "Capuche en fourrure de loup",
        wolfpelt: "Fourrure de loup",
        wooden_stick: "Baton de bois",
        woodstorage: "Stock de bois",
        wood_storage: "Stock de bois",
        worktable: "Table de travail",
        sizla: "Sizla",
        hatchet: "Hachette",
        rag: "Rags",
        lumber_pile: "Pile de planches",
        hacksaw: "Scie",
        wooden_log: "Tronc",
        saline_bag_iv: "Solution saline IV",
        saline_bag: "Solution saline",
        iv_start_kit: "IV Start kit",
        blood_bag_iv: "Poche de sang IV",
        blood_bag_kit: "Poche de sang kit",
        fireplace_furnace: "Feu de camp four",
        fireplace_stone: "Feu de camp pierre",
        spear: "Lance",
        fence_kit: "Kit de porte",
        watchtower_kit: "Kit de tour de guet",
        wooden_crate: "Boite en bois",
        workbench: "Table de travail",
        sunshade: "Pare soleil",
        wellkit: "Kit de puit",
        baseflag: "Drapeau blanc",
        well_bucket: "Seau de puit",
        armor_rack_kit: "Kit de support d'arme",
        human_steak_meat: "Viande humaine",
        patch_aus1: "Patch AUS1",
        patch_aus2: "Patch AUS2",
        patch_can1: "Patch CAN1",
        patch_can2: "Patch CAN2",
        patch_cobra: "Patch Cobra",
        patch_eod: "Patch EOD",
        patch_gnr: "Patch GNR",
        patch_med: "Patch MED",
        patch_rfl: "Patch RFL",
        patch_sl: "Patch SL",
        patch_snpr: "Patch SNPR",
        patch_tl: "Patch TL",
        patch_uk1: "Patch UK1",
        patch_uk2: "Patch UK2",
        patch_us1: "Patch US1",
        patch_us2: "Patch US2",
    },
};