window.T = window.T || {};

window.T.baseRecipes = [
    // MODS CRAFTS

    // OP_BaseItems
    {
        "name":"worktable",
        "ingredients":[
            {
                "quantity":"2",
                "item":"planks"
            },
            {
                "quantity":"10",
                "item":"nails"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"woodstorage",
        "ingredients":[
            {
                "quantity":"2",
                "item":"planks"
            },
            {
                "quantity":"10",
                "item":"nails"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"barrel_frame",
        "ingredients":[
            {
                "quantity":"2",
                "item":"planks"
            },
            {
                "quantity":"10",
                "item":"nails"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"gardenbox",
        "ingredients":[
            {
                "quantity":"2",
                "item":"planks"
            },
            {
                "quantity":"10",
                "item":"nails"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"improvised_tent",
        "ingredients":[
            {
                "quantity":"1",
                "item":"long_wooden_stick"
            },
            {
                "quantity":"1",
                "item":"burlap_sack"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"locker",
        "ingredients":[
            {
                "quantity":"10",
                "item":"metal_plates"
            },
            {
                "quantity":"1",
                "item":"pliers"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"bannermount",
        "ingredients":[
            {
                "quantity":"10",
                "item":"metal_plates"
            },
            {
                "quantity":"1",
                "item":"pliers"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"shed_crafting_kit",
        "ingredients":[
            {
                "quantity":"5",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"rope"
            }
        ],
        "mod": "OP_BaseItems",
    },
    {
        "name":"banners",
        "ingredients":[
            {
                "quantity":"1",
                "item":"camonet"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "OP_BaseItems",
    },

    // MunghardsItemPack
    {
        "name":"gunwall_wood",
        "ingredients":[
            {
                "quantity":"10",
                "item":"planks"
            },
            {
                "quantity":"5",
                "item":"metal_plates"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"gunwall_metal",
        "ingredients":[
            {
                "quantity":"10",
                "item":"planks"
            },
            {
                "quantity":"5",
                "item":"metal_plates"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"make_shift_tent_a",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"long_wooden_stick"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"make_shift_tent_b",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"long_wooden_stick"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"joint",
        "ingredients":[
            {
                "quantity":"1",
                "item":"cannabis"
            },
            {
                "quantity":"1",
                "item":"sizla"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"barbwire_baseball_bat",
        "ingredients":[
            {
                "quantity":"1",
                "item":"baseball_bat"
            },
            {
                "quantity":"1",
                "item":"barbwire"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"poncho_ghillie",
        "ingredients":[
            {
                "quantity":"1",
                "item":"camonet"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"decoy_grenade",
        "ingredients":[
            {
                "quantity":"1",
                "item":"sodacan"
            },
            {
                "quantity":"1",
                "item":"bullet"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"sandwich",
        "ingredients":[
            {
                "quantity":"1",
                "item":"jest_wonderbread"
            },
            {
                "quantity":"1",
                "item":"food_item"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"tripwire_trap",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"metalwire"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"wolffur_cowl",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wolfpelt"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "MunghardsItemPack",
    },
    {
        "name":"bearfur_cowl",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bearpelt"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "MunghardsItemPack",
    },

    // MuchStuffPack
    {
        "name":"fireplace_railing",
        "ingredients":[
            {
                "quantity":"1",
                "item":"pliers"
            },
            {
                "quantity":"1",
                "item":"metal_plates"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"planter_box",
        "ingredients":[
            {
                "quantity":"50%",
                "item":"epoxy_putty"
            },
            {
                "quantity":"10",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"square_planter_box",
        "ingredients":[
            {
                "quantity":"25%",
                "item":"epoxy_putty"
            },
            {
                "quantity":"5",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"large_ammo_box",
        "ingredients":[
            {
                "quantity":"1",
                "item":"pliers"
            },
            {
                "quantity":"2",
                "item":"metal_plates"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"american_apple_crate",
        "ingredients":[
            {
                "quantity":"1",
                "item":"hammer"
            },
            {
                "quantity":"2",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"apple_crate",
        "ingredients":[
            {
                "quantity":"1",
                "item":"hammer"
            },
            {
                "quantity":"2",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"darkwood_water_barrel_stand",
        "ingredients":[
            {
                "quantity":"1",
                "item":"hammer"
            },
            {
                "quantity":"5",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"water_barrel_stand",
        "ingredients":[
            {
                "quantity":"1",
                "item":"hammer"
            },
            {
                "quantity":"5",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"darkwood_water_barrel",
        "ingredients":[
            {
                "quantity":"50%",
                "item":"epoxy_putty"
            },
            {
                "quantity":"20",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"water_barrel",
        "ingredients":[
            {
                "quantity":"50%",
                "item":"epoxy_putty"
            },
            {
                "quantity":"20",
                "item":"planks"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"darkwood_water_barrel_valve",
        "ingredients":[
            {
                "quantity":"1",
                "item":"knife"
            },
            {
                "quantity":"1",
                "item":"firewood"
            }
        ],
        "mod": "MuchStuffPack",
    },
    {
        "name":"water_barrel_valve",
        "ingredients":[
            {
                "quantity":"1",
                "item":"knife"
            },
            {
                "quantity":"1",
                "item":"firewood"
            }
        ],
        "mod": "MuchStuffPack",
    },
    
    // CannabisPlus
    {
        "name":"cigarettes",
        "ingredients":[
            {
                "quantity":"1",
                "item":"paper"
            },
            {
                "quantity":"1",
                "item":"tobacco"
            }
        ],
        "mod": "CannabisPlus",
    },
    {
        "name":"marijuana_cigarettes",
        "ingredients":[
            {
                "quantity":"1",
                "item":"cigarettes"
            },
            {
                "quantity":"1",
                "item":"cannabis"
            }
        ],
        "mod": "CannabisPlus",
    },
    {
        "name":"cannabis_bag",
        "ingredients":[
            {
                "quantity":"1",
                "item":"cannabis"
            },
            {
                "quantity":"1",
                "item":"cannabis"
            }
        ],
        "mod": "CannabisPlus",
    },
    {
        "name":"cannabis_brick",
        "ingredients":[
            {
                "quantity":"16",
                "item":"cannabis_bag"
            },
            {
                "quantity":"1",
                "item":"duct_tape"
            }
        ],
        "mod": "CannabisPlus",
    },

    // BaseFurnitureMods
    {
        "name":"tag_ammo",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },
    {
        "name":"tag_clothing",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },
    {
        "name":"tag_component",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },
    {
        "name":"tag_construction",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },
    {
        "name":"tag_magazine",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },
    {
        "name":"tag_medical",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },
    {
        "name":"tag_weapon",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },
    {
        "name":"tag_tools",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bark_oak"
            },
            {
                "quantity":"2",
                "item":"nails"
            }
        ],
        "mod": "BaseFurnitureMods",
    },

    // BaseBuildingPlus
    {
        "name":"workbench",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_log"
            },
            {
                "quantity":"5",
                "item":"planks"
            }
        ],
        "mod": "BaseBuildingPlus",
    },
    {
        "name":"sunshade",
        "ingredients":[
            {
                "quantity":"5",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"camonet"
            }
        ],
        "mod": "BaseBuildingPlus",
    },
    {
        "name":"wood_storage",
        "ingredients":[
            {
                "quantity":"20",
                "item":"nails"
            },
            {
                "quantity":"10",
                "item":"planks"
            }
        ],
        "mod": "BaseBuildingPlus",
    },
    {
        "name":"wellkit",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rope"
            },
            {
                "quantity":"1",
                "item":"well_bucket"
            }
        ],
        "mod": "BaseBuildingPlus",
    },
    {
        "name":"baseflag",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "BaseBuildingPlus",
    },

    // ModularVestSystem
    {
        "name":"armor_rack_kit",
        "ingredients":[
            {
                "quantity":"10",
                "item":"planks"
            },
            {
                "quantity":"10",
                "item":"nails"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_aus1",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_aus2",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_can1",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_can2",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_cobra",
        "ingredients":[
            {
                "quantity":"1",
                "item":"human_steak_meat"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_eod",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_gnr",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_med",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_rfl",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_sl",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_snpr",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_tl",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_uk1",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_uk2",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_us1",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },
    {
        "name":"patch_us2",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rag"
            },
            {
                "quantity":"1",
                "item":"sewing_kit"
            }
        ],
        "mod": "ModularVestSystem",
    },

    // MedicalAttention
    {
        "name":"splint",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bandage"
            },
            {
                "quantity":"2",
                "item":"wooden_stick"
            }
        ],
        "mod": "MedicalAttention",
    },
    {
        "name":"splint",
        "ingredients":[
            {
                "quantity":"1",
                "item":"duct_tape"
            },
            {
                "quantity":"2",
                "item":"wooden_stick"
            }
        ],
        "mod": "MedicalAttention",
    },


    // Vanilla crafts
    {
        "name":"burlap_strips",
        "ingredients":[
            {
                "quantity":"1",
                "item":"burlap_sack"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"rope",
        "ingredients":[
            {
                "quantity":"100%",
                "item":"pile_of_guts"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"rope",
        "ingredients":[
            {
                "quantity":"6",
                "item":"rag"
            },
            {
                "quantity":"6",
                "item":"rag"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"wooden_stick",
        "ingredients":[
            {
                "quantity":"1",
                "item":"long_wooden_stick"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"wooden_stick",
        "ingredients":[
            {
                "quantity":"1",
                "item":"firewood"
            },
            {
                "quantity":"1",
                "item":"hatchet"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"planks",
        "ingredients":[
            {
                "quantity":"1",
                "item":"lumber_pile"
            },
            {
                "quantity":"1",
                "item":"hatchet"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"planks",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_log"
            },
            {
                "quantity":"1",
                "item":"hacksaw"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"saline_bag_iv",
        "ingredients":[
            {
                "quantity":"1",
                "item":"saline_bag"
            },
            {
                "quantity":"1",
                "item":"iv_start_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"blood_bag_iv",
        "ingredients":[
            {
                "quantity":"1",
                "item":"blood_bag_kit"
            },
            {
                "quantity":"1",
                "item":"iv_start_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"small_stone",
        "ingredients":[
            {
                "quantity":"1",
                "item":"stone"
            },
            {
                "quantity":"1",
                "item":"pickaxe"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"tanned_leather",
        "ingredients":[
            {
                "quantity":"1",
                "item":"deer_pelt"
            },
            {
                "quantity":"10/30%",
                "item":"garden_lime"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"improvised_courier_bag",
        "ingredients":[
            {
                "quantity":"1",
                "item":"burlap_sack"
            },
            {
                "quantity":"1",
                "item":"rope"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_courier_bag",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wild_boar_pelt"
            },
            {
                "quantity":"1",
                "item":"rope"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"improvised_courier_backpack",
        "ingredients":[
            {
                "quantity":"1",
                "item":"improvised_courier_bag"
            },
            {
                "quantity":"3",
                "item":"wooden_stick"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"improvised_leather_backpack",
        "ingredients":[
            {
                "quantity":"1",
                "item":"improvised_leather_bag"
            },
            {
                "quantity":"3",
                "item":"wooden_stick"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_sack",
        "ingredients":[
            {
                "quantity":"1",
                "item":"tanned_leather"
            },
            {
                "quantity":"1",
                "item":"leather_sewing_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"ghillie_hood",
        "ingredients":[
            {
                "quantity":"2",
                "item":"burlap_strips"
            },
            {
                "quantity":"1",
                "item":"netting"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"ghillie_bushrag",
        "ingredients":[
            {
                "quantity":"4",
                "item":"burlap_strips"
            },
            {
                "quantity":"2",
                "item":"netting"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"ghillie_suit",
        "ingredients":[
            {
                "quantity":"10",
                "item":"burlap_strips"
            },
            {
                "quantity":"4",
                "item":"netting"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"ghillie_top",
        "ingredients":[
            {
                "quantity":"6",
                "item":"burlap_strips"
            },
            {
                "quantity":"3",
                "item":"netting"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"ghillie_gun_wrap",
        "ingredients":[
            {
                "quantity":"2",
                "item":"burlap_strips"
            },
            {
                "quantity":"1",
                "item":"netting"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_hat",
        "ingredients":[
            {
                "quantity":"1",
                "item":"tanned_leather"
            },
            {
                "quantity":"1",
                "item":"leather_sewing_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_jacket",
        "ingredients":[
            {
                "quantity":"5",
                "item":"tanned_leather"
            },
            {
                "quantity":"1",
                "item":"leather_sewing_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_storage_vest",
        "ingredients":[
            {
                "quantity":"2",
                "item":"tanned_leather"
            },
            {
                "quantity":"1",
                "item":"leather_sewing_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_pants",
        "ingredients":[
            {
                "quantity":"3",
                "item":"tanned_leather"
            },
            {
                "quantity":"1",
                "item":"leather_sewing_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_moccassins",
        "ingredients":[
            {
                "quantity":"4",
                "item":"tanned_leather"
            },
            {
                "quantity":"1",
                "item":"leather_sewing_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"leather_water_pouch",
        "ingredients":[
            {
                "quantity":"1",
                "item":"tanned_leather"
            },
            {
                "quantity":"1",
                "item":"leather_sewing_kit"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"bark_birch"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"paper"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"bark_oak"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"firewood"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"rag"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"bandage"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace_stone",
        "ingredients":[
            {
                "quantity":"1",
                "item":"fireplace"
            },
            {
                "quantity":"8",
                "item":"stone"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fireplace_furnace",
        "ingredients":[
            {
                "quantity":"1",
                "item":"fireplace"
            },
            {
                "quantity":"16",
                "item":"stone"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"torch",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"animal_lard"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"hand_drill_kit",
        "ingredients":[
            {
                "quantity":"1",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"bark_oak"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"improvised_fishing_rod",
        "ingredients":[
            {
                "quantity":"1",
                "item":"rope"
            },
            {
                "quantity":"1",
                "item":"long_wooden_stick"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"bone_fishing_hook",
        "ingredients":[
            {
                "quantity":"1",
                "item":"bones"
            },
            {
                "quantity":"1",
                "item":"knife"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"spiked_baseball_bat",
        "ingredients":[
            {
                "quantity":"1",
                "item":"baseball_bat"
            },
            {
                "quantity":"13",
                "item":"nails"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"improvised_suppressor",
        "ingredients":[
            {
                "quantity":"1",
                "item":"pet_bottle"
            },
            {
                "quantity":"1",
                "item":"duct_tape"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"garden_lime",
        "ingredients":[
            {
                "quantity":"10%",
                "item":"pile_of_guts"
            },
            {
                "quantity":"10%",
                "item":"plants_material"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"spear",
        "ingredients":[
            {
                "quantity":"1",
                "item":"long_wooden_stick"
            },
            {
                "quantity":"1",
                "item":"bones"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"fence_kit",
        "ingredients":[
            {
                "quantity":"2",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"rope"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"watchtower_kit",
        "ingredients":[
            {
                "quantity":"2",
                "item":"wooden_stick"
            },
            {
                "quantity":"1",
                "item":"rope"
            }
        ],
        "mod": "Vanilla",
    },
    {
        "name":"wooden_crate",
        "ingredients":[
            {
                "quantity":"2",
                "item":"planks"
            },
            {
                "quantity":"10",
                "item":"nails"
            }
        ],
        "mod": "Vanilla",
    },
];